"use client";

import type { CampaignPlan } from "@motiongrid/domain";
import {
  ArrowRight,
  Check,
  CircleDollarSign,
  Clock3,
  LoaderCircle,
  ShieldCheck,
  Sparkles,
} from "lucide-react";
import { FormEvent, useState } from "react";

const examplePlan: CampaignPlan = {
  campaignId: "preview",
  motion: "business",
  mode: "local-discovery",
  rationale: "Local businesses can be discovered, checked for an online-booking gap and ranked before any paid contact or outreach action.",
  assumptions: ["Bangalore is the target geography", "Independent locations only"],
  expectedTargets: 120,
  estimatedCostUsd: 18.4,
  steps: [
    { id: "discover", title: "Discover", capability: "search_local_businesses", behavior: "read", approvalRequired: false },
    { id: "analyze", title: "Analyze", capability: "analyze_business_evidence", behavior: "read", approvalRequired: false },
    { id: "score", title: "Score", capability: "score_b2b_opportunity", behavior: "read", approvalRequired: false },
    { id: "contacts", title: "Contacts", capability: "find_decision_makers", behavior: "read", approvalRequired: false },
    { id: "outreach", title: "Approve", capability: "send_sales_outreach", behavior: "write", approvalRequired: true },
  ],
  risks: ["Provider cost may change after the geography is resolved."],
  successMetrics: ["Qualified opportunities", "Booked demos"],
};

export function CampaignWorkbench() {
  const [objective, setObjective] = useState(
    "Find independent gyms in Bangalore without online booking and generate 20 qualified demos.",
  );
  const [plan, setPlan] = useState<CampaignPlan>(examplePlan);
  const [status, setStatus] = useState<"idle" | "planning" | "ready" | "error">("idle");
  const [message, setMessage] = useState("Preview route — connect the Mastra runtime to generate live plans.");

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setStatus("planning");
    setMessage("Interpreting objective and constructing the route…");

    try {
      const response = await fetch("/api/campaigns", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          workspaceId: "workspace-preview",
          campaignId: crypto.randomUUID(),
          objective,
        }),
      });
      const payload = await response.json();

      if (!response.ok) {
        throw new Error(payload.error ?? "Campaign planning failed.");
      }

      setPlan(payload);
      setStatus("ready");
      setMessage("Plan generated by the Mastra runtime. No external action has been taken.");
    } catch (error) {
      setStatus("error");
      setMessage(error instanceof Error ? error.message : "Campaign planning failed.");
    }
  }

  return (
    <section className="workbench" id="workbench" aria-labelledby="workbench-title">
      <div className="workbench-bar">
        <div>
          <span className="status-light" />
          <span id="workbench-title">Campaign workbench</span>
        </div>
        <span className="mono-label">PLAN / 001</span>
      </div>

      <div className="workbench-grid">
        <form className="objective-panel" onSubmit={submit}>
          <div className="panel-kicker">
            <Sparkles size={14} /> Objective
          </div>
          <label htmlFor="objective">What outcome should MotionGrid build toward?</label>
          <textarea
            id="objective"
            value={objective}
            onChange={(event) => setObjective(event.target.value)}
            minLength={12}
            maxLength={2000}
          />
          <div className="objective-meta">
            <span>Plain language is enough</span>
            <span>{objective.length}/2000</span>
          </div>
          <button className="primary-button" type="submit" disabled={status === "planning"}>
            {status === "planning" ? (
              <><LoaderCircle className="spin" size={17} /> Constructing plan</>
            ) : (
              <>Build campaign plan <ArrowRight size={17} /></>
            )}
          </button>
          <p className={`runtime-note runtime-note--${status}`} aria-live="polite">{message}</p>
        </form>

        <div className="route-panel">
          <div className="route-heading">
            <div>
              <span className="eyebrow">Selected motion</span>
              <strong>Business / Local discovery</strong>
            </div>
            <span className="confidence">92% fit</span>
          </div>

          <div className="route-map" aria-label="Proposed campaign route">
            {plan.steps.map((step, index) => (
              <div className="route-step" key={step.id}>
                <div className={`route-node ${step.approvalRequired ? "route-node--approval" : ""}`}>
                  {step.approvalRequired ? <ShieldCheck size={16} /> : index + 1}
                </div>
                <span>{step.title}</span>
                {index < plan.steps.length - 1 && <span className="route-line" />}
              </div>
            ))}
          </div>

          <div className="plan-ledger">
            <div>
              <CircleDollarSign size={16} />
              <span>Estimated cost</span>
              <strong>${plan.estimatedCostUsd.toFixed(2)}</strong>
            </div>
            <div>
              <Clock3 size={16} />
              <span>Expected targets</span>
              <strong>{plan.expectedTargets}</strong>
            </div>
            <div>
              <ShieldCheck size={16} />
              <span>External actions</span>
              <strong>Approval required</strong>
            </div>
          </div>

          <div className="evidence-note">
            <Check size={15} />
            <span>Every qualification will retain its source, confidence and observed time.</span>
          </div>
        </div>
      </div>
    </section>
  );
}
